export type TutorialPosition = "top" | "bottom" | "left" | "right" | "center";
export type TutorialStep = { id:string; route:string; target?:string; icon:string; title:string; description:string; position?:TutorialPosition };
export type TutorialDefinition = { id:string; category:string; title:string; summary:string; steps:TutorialStep[] };
const page=(id:string,route:string,icon:string,title:string,description:string):TutorialStep=>({id,route,icon,title,description,target:".private-tab-page",position:"center"});
export const tutorials:TutorialDefinition[]=[
{id:"main-tour",category:"Getting Started",title:"SMAJ PI HUB essentials",summary:"Learn the five main areas of your SMAJ PI HUB account.",steps:[
{id:"home",route:"/dashboard",target:'[data-tour="home"]',icon:"home",title:"Home",description:"Return to your dashboard, activity and personalized updates from here.",position:"top"},
{id:"services",route:"/dashboard",target:'[data-tour="services"]',icon:"services",title:"Services",description:"Open Store, Jobs, Education, Stream and every connected SMAJ service.",position:"top"},
{id:"search",route:"/dashboard",target:'[data-tour="search"]',icon:"search",title:"Search",description:"Find products, services, people and opportunities across SMAJ PI HUB.",position:"top"},
{id:"messages",route:"/dashboard",target:'[data-tour="messages"]',icon:"messages",title:"Messages",description:"Keep buyer, seller and service conversations together in one inbox.",position:"top"},
{id:"you",route:"/dashboard",target:'[data-tour="you"]',icon:"profile",title:"You and your profile",description:"Manage your profile, preferences, wallet tools and account safety.",position:"top"},
{id:"finish",route:"/dashboard",icon:"done",title:"You are ready",description:"Explore at your own pace. Replay this tour or open a detailed guide anytime from Help.",position:"center"}]},
{id:"buy-product",category:"Marketplace",title:"How to buy a product",summary:"Search, review and safely place a marketplace order.",steps:[page("find","/search","search","Find a product","Use Search or Store, then choose the product you want."),page("review","/app/services/store","store","Review the listing","Check seller, price and delivery details before continuing.")]},
{id:"sell-product",category:"Seller Tools",title:"How to sell a product",summary:"Create a listing and publish it from Seller Tools.",steps:[page("seller","/seller","seller","Open Seller Tools","Use your seller workspace to manage products and orders."),page("create","/add-product","add","Add your product","Add clear photos, accurate details, price and delivery information.")]},
{id:"seller-setup",category:"Seller Tools",title:"Seller setup",summary:"Prepare your seller profile and store presence.",steps:[page("profile","/profile","profile","Complete your seller profile","Add accurate business and contact information."),page("safety","/settings","safety","Review account safety","Keep account and contact preferences current.")]},
{id:"pi-payment",category:"Payments",title:"Pi payments",summary:"Understand payment review and confirmation.",steps:[page("wallet","/app/wallet","payment","Open your wallet area","Review your account and available payment tools."),page("confirm","/app/wallet","safety","Confirm every request","Always check the amount and recipient. Payments are never queued offline.")]},
{id:"find-work",category:"Jobs",title:"Find work",summary:"Search opportunities and submit a strong application.",steps:[page("browse","/services/jobs","jobs","Browse jobs","Search and filter opportunities that match your skills."),page("apply","/services/jobs","done","Review and apply","Read the details and submit complete information.")]},
{id:"hire-talent",category:"Jobs",title:"Hire talent and manage payment",summary:"Post a role and manage the hiring flow.",steps:[page("employer","/services/jobs/employer","jobs","Employer workspace","Register or select your company before posting."),page("manage","/services/jobs/employer","messages","Review candidates","Use applications and messages to manage the process safely.")]},
{id:"education",category:"Education",title:"Education enrollment",summary:"Discover courses and follow enrollment.",steps:[page("discover","/services/education","education","Discover learning","Browse courses, tutors and institutions."),page("enroll","/services/education","done","Review before enrolling","Check provider, requirements, certificate and fees.")]},
{id:"stream",category:"Stream",title:"Using Stream",summary:"Discover, watch and manage supported media.",steps:[page("discover","/app/services/stream","stream","Discover Stream","Browse titles and open one to view details."),page("watch","/app/services/stream","play","Use the player","Controls appear on interaction; supported downloads are identified.")]},
{id:"messages",category:"Messages",title:"Messages and contacting sellers",summary:"Start and manage conversations.",steps:[page("start","/messages","messages","Open your inbox","Buyer, seller and service conversations appear here."),page("safe","/messages","safety","Keep conversations safe","Never share sensitive credentials.")]},
{id:"orders",category:"Marketplace",title:"Orders",summary:"Track purchase and seller activity.",steps:[page("orders","/orders","orders","Open Orders","Review status, details and related conversations."),page("updates","/notifications","messages","Follow updates","Important order actions also appear in Notifications.")]},
{id:"account-safety",category:"Account & Safety",title:"Account and safety",summary:"Manage profile, devices and security.",steps:[page("account","/settings","profile","Review your account","Keep profile and preferences current."),page("devices","/settings/devices","safety","Manage sessions","Remove devices you no longer recognize.")]}
];
export const TUTORIAL_OPEN_EVENT="smaj:tutorial-open";
export const tutorialById=(id:string)=>tutorials.find(t=>t.id===id);
export const tutorialStorageKey=(userId:string|undefined,id:string)=>`smaj_tutorial:${userId||"guest"}:${id}`;
